name: VACCINE-CI
on:
 push:
   branches:
     - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Use Node.js 14'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - run: pm2 restart App
