name: VACCINE-CI
on:
 push:
   branches:
     - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Use Node.js 14'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install on backend
        run: |
          cd ./server
          npm install
          npm start &
      - name: npm install on frontend
        run: |
          cd ./webapp
          npm install
          npm run build
          npm run start-prod &
